version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "15.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    restart: always
    container_name: egov-odoo
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      DB_FILTER: "prod"
      PGDATABASE: "prod"
      LIST_DB: "true"
      PROXY_MODE: "true"
    volumes:
      - filestore:/var/lib/odoo:z
    networks:
      default:
    tty: true
    depends_on:
      - db

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:13-alpine
    restart: always
    container_name: egov-db
    env_file:
      - .docker/db-creation.env
    volumes:
      - db:/var/lib/postgresql/data:z
    networks:
      default:

  nginx:
    image: nginx:1.24.0
    restart: always
    container_name: egov-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - ./nginx_config:/etc/nginx/conf.d
    networks:
      default:

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  db:
  filestore:
