version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      PYTHONOPTIMIZE: ""
      INITIAL_LANG: "en_US"
      DB_FILTER: "prod"
      PGDATABASE: &dbname prod
    volumes:
      - ./odoo/custom:/opt/odoo/custom:rw,z
      - ./odoo/auto:/opt/odoo/auto:rw,z
      - /opt/odoo/custom/src/odoo
    networks:
      mynetwork:
        ipv4_address: 172.20.0.10
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - nginx:/etc/nginx/
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12

networks:
  mynetwork:
    driver_opts:
      encrypted: 1
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  filestore:
  db:
  nginx:
